#!/usr/bin/env bash
# install load balancer
sudo apt-get install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get install haproxy=1.8.\*
sudo echo -e "\nlisten www" >> /etc/haproxy/haproxy.cfg
sudo echo -e "\tbind :80" >> /etc/haproxy/haproxy.cfg
sudo echo -e "\tbalance roundrobin" >> /etc/haproxy/haproxy.cfg
sudo echo -e "\tserver 1501-web-01 34.73.23.33" >> /etc/haproxy/haproxy.cfg
sudo echo -e "\tserver 1501-web-02 	34.236.145.76" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
