#!/usr/bin/env bash
#Write a Bash script that use SINGNALS.

trap "sudo rm -f /var/run/holbertonscript.pid; exit" SIGQUIT
trap "echo I hate the kill command; sudo rm -f /var/run/holbertonscript.pid; exit" SIGTERM
trap "echo Y U no love me?!; exit" SIGINT
touch /var/run/holbertonscript.pid
while true
do
    echo "To infinity and beyond"
    sleep 2
done