#!/usr/bin/env bash
# Fizzbuzz

for i in {1..100}
do
    if [ $(( i%15 )) -eq 0 ]
    then
        printf "Fizzbuzz\n"
    elif [ $(( i%5 )) -eq 0 ]
    then
        printf "Buzz\n"
    elif [ $(( i%3 )) -eq 0 ]
    then
        printf "Fizz\n"
    else
        printf "%d\n" $i  
    fi
done
